#! /bin/sh

# Program to generate protoypes

cat <<"EOP" > proto_h
/* ************************************************************** *
 * proto_h - Prototypes for functions in dis68                    $
 *                                                                $
 * This file handles both STDC and non-STDC forms                 $
 * $Id::                                                          $
 * ************************************************************** */

#ifdef __STDC__
EOP

cproto *.c >> proto_h
echo -e "\n#else\n" >> proto_h
cproto -f1 *.c >> proto_h
echo -e "#endif\n" >> proto_h

rm proto.h
mv proto_h proto.h
