#! /bin/bash

# Program to generate protoypes

# Empty proto.h so it won't interfere with this run
echo >proto.h

cat <<"EOP" > proto_h
/* ************************************************************** *
 * proto_h - Prototypes for functions in dis68                    $
 *                                                                $
 * This file handles both STDC and non-STDC forms                 $
 * $Id::                                                          $
 * ************************************************************** */

#ifndef _HAVEPROTO_
#define _HAVEPROTO_
#ifdef __STDC__
EOP

cproto -I. *.c >> proto_h
echo -e "\n#else\n" >> proto_h
cproto -f1 *.c >> proto_h
echo -e "#endif   /* __STDC__*/\n" >> proto_h
echo -e "#endif   /* #ifndef _HAVEPROTO_*/\n" >> proto_h

rm proto.h
mv proto_h proto.h
